Traceback (most recent call last):
  File "/users2/cpca56132020/moliveira/RepairThemAll/script/core/runner/local/LocalRunner.py", line 41, in run
    task.run()
  File "/users2/cpca56132020/moliveira/RepairThemAll/script/core/runner/RepairTask.py", line 30, in run
    return self.tool.repair(self)
  File "/users2/cpca56132020/moliveira/RepairThemAll/script/core/repair_tools/Nopol.py", line 96, in repair
    repair_task.results = json.load(fd)
  File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
